### ISSUE TITLE
Issues with Odd-numbered Signal Length in VMD-RS Build

### ISSUE THREAD

**Issue by Deace** [jiafuei/vmd-rs#3]
I followed the instructions to build the project with Rust and imported VMD from "vmdpy". However, the inconsistency in length still persists when I use an odd-numbered signal length. Did I fail to build vmd-rs properly?

**Comment by soyasoya5** [comment]
@Deace Not sure if I understand the problem here. How did you **build** and **use** this project?

This project is meant to be used by Rust programs. If you're looking to use it in Python, check out https://github.com/jiafuei/vmdrs-py.

Just so you dont waste time digging through the code, try the following

1. `pip install vmdrs-py`

```py
from vmdrs_py import VMD

# Your code here...
```

If you have any issues installing/building the python version, open an issue in that repo and i'll try to help.

**Comment by jiafuei** [comment]
> I followed the instructions to build the project with Rust and imported VMD from "vmdpy". However, the inconsistency in length still persists when I use an odd-numbered signal length. Did I fail to build vmd-rs properly?

^ try the solution suggested by that user. @Deace
